[versions]

# Common
java = "21"
licenser = "0.7.5"

# Vanilla
minecraft = "1.21.5"
# https://parchmentmc.org/docs/getting-started
parchment_minecraft = "1.21.4"
parchment_version = "2025.03.23"
vanilla_gradle = "0.2.1-SNAPSHOT"

# NeoForge
# https://projects.neoforged.net/neoforged/moddevgradle
neoforge_gradle = "2.0.80"
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version = "21.5.22-beta"

# Fabric
# https://fabricmc.net/develop/
fabric_loom = "1.10-SNAPSHOT"
fabric_loader = "0.16.12"
fabric_api = "0.119.6+1.21.5"

[libraries]

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

[bundles]

fabric = [ "fabric_loader", "fabric_api" ]

[plugins]

licenser = { id = "net.neoforged.licenser", version.ref = "licenser" }
vanilla_gradle = { id = "org.spongepowered.gradle.vanilla", version.ref = "vanilla_gradle" }
neoforge_gradle = { id = "net.neoforged.moddev", version.ref = "neoforge_gradle" }
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
